# Generated by Django 4.0.10 on 2023-03-23 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_books_cover'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'permissions': [('special_status', 'Can read all books')]},
        ),
    ]
